app:
  name: song-service
  description: Song Service for metadata management
  version: 1.0.0

server:
  port: 8082
spring:
  application:
    name: song-service
  datasource:
    url: jdbc:postgresql://localhost:5433/song-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    processor_queue: processor-queue
    mp3song_queue: mp3song-queue
  jpa:
    hibernate:
      ddl-auto: update   # або: validate, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
